// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVeiculos.Data;

#nullable disable

namespace webveiculos.Migrations
{
    [DbContext(typeof(WebVeiculosContext))]
    partial class WebVeiculosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebVeiculos.Models.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("INT")
                        .HasColumnName("Ano");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Combustivel");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Cor");

                    b.Property<int>("LitragemPortaMalas")
                        .HasColumnType("INT")
                        .HasColumnName("LitragemPortaMalas");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Placa");

                    b.Property<int>("QtdPortas")
                        .HasColumnType("INT")
                        .HasColumnName("QtdPortas");

                    b.HasKey("Id");

                    b.ToTable("Carros", (string)null);
                });

            modelBuilder.Entity("WebVeiculos.Models.Onibus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("INT")
                        .HasColumnName("Ano");

                    b.Property<int>("Combustivel")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Placa");

                    b.Property<bool>("PossuiBanheiro")
                        .HasColumnType("BIT")
                        .HasColumnName("PossuiBanheiro");

                    b.Property<bool>("PossuiTomada")
                        .HasColumnType("BIT")
                        .HasColumnName("PossuiTomada");

                    b.Property<bool>("PossuiTv")
                        .HasColumnType("BIT")
                        .HasColumnName("PossuiTv");

                    b.Property<bool>("PossuiWifi")
                        .HasColumnType("BIT")
                        .HasColumnName("PossuiWifi");

                    b.Property<int>("QtdAssentos")
                        .HasColumnType("INT")
                        .HasColumnName("QtdAssentos");

                    b.HasKey("Id");

                    b.ToTable("Onibus", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
